name: Build via EESSI and EasyBuild on x86 and Arm
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:  # Allows manual triggering
  push:
  pull_request:
    branches:
      - main
# Declare default permissions as read only.
permissions: read-all
jobs:
  minimal_usage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: Load EESSI
      uses: eessi/github-action-eessi@v3
      with:
        eessi_stack_version: '2025.06'
    - name: Cache MPICH/GCC install
      id: cache-mpich-gcc
      uses: actions/cache@v5
      with:
        path: /home/runner/work/mpich/eessi
        key: mpich-gcc-${{ matrix.os }}-5.0.1-v3-${{ github.sha }}
        # 2. This prefix pulls your existing cache as a starting point at the beginning
        restore-keys: mpich-gcc-${{ matrix.os }}-5.0.1-v3
    - name: Install MPICH
      shell: bash
      run: |
        export EESSI_PROJECT_INSTALL="/home/runner/work/mpich/eessi"
        export EASYBUILD_SOURCEPATH="/home/runner/work/mpich/eessi/sources"
        mkdir -p $EESSI_PROJECT_INSTALL
        module load EESSI-extend
        cd easybuild
        
        # Grab the source files first
        eb --fetch MPICH-5.0.1-GCC-14.3.0.eb
        
        # Then run the two builds in parallel
        # (with and without mpif)
        eb --robot MPICH-5.0.1-GCC-14.3.0-mpif.eb &
        pid1=$!
        eb --robot MPICH-5.0.1-GCC-14.3.0.eb
        pid2=$!
        wait $pid1
        wait $pid2

    - name: Test trampi via EESSI-extend
      shell: bash
      run: |
        export EESSI_PROJECT_INSTALL="/home/runner/work/mpich/eessi"
        export EESSI_USER_INSTALL="/home/runner/work/eessi"
        mkdir -p $EESSI_USER_INSTALL
        module load EESSI-extend
        unset EASYBUILD_DEBUG
        if ! eb --software-commit="$GITHUB_SHA" easybuild/trampi-devel-GCC-14.3.0.eb; then
          echo
          echo "EasyBuild failed. Last log:"
          echo
          cat "$(eb --last-log)"
          exit 1
        fi
        echo
        echo "Check we can load the module:"
        echo
        module load trampi
        module list
        echo ""
        echo "Check the mpicc compiler works:"
        echo ""
        mpicc -show
        mpicc -Werror -Wl,--fatal-warnings test_codes/mpi_hello_world.c
        echo ""
        echo "Check how the executable is linked:"
        echo ""
        ldd ./a.out
        echo ""
        echo "Check we can also run things:"
        echo ""
        LD_LIBRARY_PATH=$EBROOTTRAMPI/lib mpiexec -n 2 ./a.out
        echo ""
        echo "Check the mpifort compiler works (with '-Werror -Wl,--fatal-warnings' ):"
        echo ""
        mpifort -show test_codes/mpi_hello_world.f90
        # mpifort -fno-align-commons test_codes/mpi_hello_world.f90
        mpifort -Werror -Wl,--fatal-warnings test_codes/mpi_hello_world.f90
        echo ""
        echo "Check how the executable is linked:"
        echo ""
        ldd ./a.out
        echo ""
        echo "Check we can also run fortran codes:"
        echo ""
        LD_LIBRARY_PATH=$EBROOTTRAMPI/lib mpirun -n 2 ./a.out
        echo ""
        echo "Check what verbose output looks like by setting TRAMPI_ABI_LIBRARY_VERBOSE:"
        echo ""
        TRAMPI_ABI_LIBRARY_VERBOSE=1 LD_LIBRARY_PATH=$EBROOTTRAMPI/lib mpirun -n 2 ./a.out
        echo ""
        echo "Check what verbose output looks like when changing the backend ABI library:"
        echo "(must use C here as that is what the backend supports in this case)"
        echo ""
        mpicc -Werror -Wl,--fatal-warnings test_codes/mpi_hello_world.c
        module load MPICH/5.0.1-GCC-14.3.0
        export TRAMPI_ABI_LIBRARY="$EBROOTMPICH/lib/libmpi_abi.so"
        module unload MPICH
        echo ""
        echo "Running:"
        echo " TRAMPI_ABI_LIBRARY_VERBOSE=1 LD_LIBRARY_PATH=$EBROOTTRAMPI/lib mpirun -n 2 ./a.out"
        echo ""
        TRAMPI_ABI_LIBRARY_VERBOSE=1 LD_LIBRARY_PATH=$EBROOTTRAMPI/lib mpirun -n 2 ./a.out
